language: php
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script: phpenv config-add .travis.php.ini
install: composer install --dev
script: php ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml
after_script: php ./vendor/bin/test-reporter --stdout --coverage-report build/logs/clover.xml
