<?php
/*
 * This file is part of CherryHttp project.
 * You are using it at your own risk and you are fully responsible
 *  for everything that code will do.
 *
 * (c) Grzegorz Zdanowski <grzegorz@noflash.pl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace noFlash\CherryHttp\Http\Response;

/**
 * I'm not 100% sure if it's good approach, but I have no better idea
 */
trait AutogeneratedResponseTrait
{
    private $template = '<html><head><title>%s</title><style>html,body{margin:0;padding:0;height:100%%;width:100%%;background:gray;font-family:sans-serif;}a{color:rgb(198,30,56);text-decoration:none;}a:hover{text-decoration:underline;}</style></head><body><div style="width:100%%;height:100%%;background:radial-gradient(ellipse at center,rgba(255,255,255,1)25%%,rgba(255,255,255,0)100%%);"><div style="text-align:center;position:relative;top:45%%;transform:translateY(-45%%);"><h1 style="font-size:10em;margin:0;color:#850927;">%s</h1><h2 style="font-size:2em;margin-top:0;color:#850927;">%s</h2><p style="font-size:1.2em;line-height:1.4em;">%s</p></div></div><div style="color:#f8f8f8;font-size:0.8em;padding:1em 0 1em 0;position:absolute;height:1em;bottom:0;left:0;right:0;background-color:rgba(46,46,46,0.7);display:block;text-align:center;">Driven by <a href="https://github.com/kiler129/CherryHttp">&#127826; CherryHTTP</a></div></body></html>';

    /**
     * Generates response with built-in template.
     *
     * @param int|string  $code         Response code which will be presented to the user.
     * @param string      $reasonPhrase Response code reason phrase displayed under the code.
     * @param string|null $title        HTML <title> tag contents. If null it will be generated from code & reason
     *                                  phrase.
     * @param string|null $description  Additional description/explanation of situation.
     *
     * @return string HTML content
     */
    public function generateAutomaticResponseContent($code, $reasonPhrase, $title = null, $description = null)
    {
        if ($title === null) {
            $title = $code . ' ' . $reasonPhrase;
        }

        return sprintf($this->template, $title, $code, $reasonPhrase, $description);
    }
}
